#Form theme can be set here and set globaly in twig config
twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']

# used in all pages
    globals:
        ga_code: GAcode-123